---
swagger: "2.0"
info:
  description: "Very simplistic API to handle notes.\n"
  version: "0.0.1"
  title: "Notes"
host: "localhost:8080"
basePath: "/"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'http://notes-server.firebaseapp.com'
    tokenUrl: 'http://notes-server.firebaseapp.com'
    scopes:
      write:notes: modify all notes
      read:notes: read all notes
security:
    - OauthSecurity: []
paths:
  /notes:
    get:
      operationId: "getAllNotes"
      parameters: []
      responses:
        200:
          description: "Get all notes"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Note"
      x-swagger-router-controller: "Default"
    post:
      operationId: "postNote"
      parameters:
      - in: "body"
        name: "note"
        description: "Text of the note we want to save"
        required: false
        schema:
          $ref: "#/definitions/Note"
      responses:
        201:
          description: "Note was correctly created"
      x-swagger-router-controller: "Default"
  /notes/{id}:
    get:
      operationId: "getNotesById"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of the note."
        required: true
        type: "string"
      responses:
        200:
          description: "Note was fetched correctly"
        404:
          description: "Note wasn't found"
      x-swagger-router-controller: "Default"
    put:
      operationId: "putNotesById"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of the note."
        required: true
        type: "string"
      - in: "body"
        name: "note"
        description: "Text of the note we want to save"
        required: false
        schema:
          $ref: "#/definitions/Note"
      responses:
        200:
          description: "Note was replaced."
        500:
          description: "Internal server error"
      x-swagger-router-controller: "Default"
    delete:
      operationId: "deleteNotesById"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of the note."
        required: true
        type: "string"
      - in: "body"
        name: "note"
        description: "Text of the note we want to save"
        required: false
        schema:
          $ref: "#/definitions/Note"
      responses:
        204:
          description: "Note was deleted"
        404:
          description: "Note missing"
      x-swagger-router-controller: "Default"
    patch:
      operationId: "patchNotesById"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of the note."
        required: true
        type: "string"
      - in: "body"
        name: "note"
        description: "Text of the note we want to save"
        required: false
        schema:
          $ref: "#/definitions/Note"
      responses:
        200:
          description: "Note was changed."
        500:
          description: "Internal server error"
      x-swagger-router-controller: "Default"
definitions:
  Note:
    type: "object"
    properties:
      id:
        type: "string"
        description: "The unique ID for the note"
      text:
        type: "string"
        description: "The note of the text"
